apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    hello.world.services: hello-world
  name: hello-world
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        hello.world.services: hello-world
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xms256m -Xmx512m
        - name: TIME_APPLY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
        image: registry.qishon.com:33000/helloword/qishon/spring-boot-helloworld:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: hello-world
        ports:
        - containerPort: 8080
        resources: {}
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
status: {}

