apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    hello.world.services: hello-world
  name: hello-world
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 11500
  selector:
    hello.world.services: hello-world
status:
  loadBalancer: {}

